/*
  Lesson 01 - Metadata,Read, add, and remove rows
  CLASS: LD01EIRT01
  Student:
  Date: 15/09/2026
*/

USE ULHT_DB26;
GO

SELECT DB_NAME() AS current_database;

SELECT * FROM INFORMATION_SCHEMA.TABLES t WHERE t.TABLE_SCHEMA = 'HR';

SELECT TOP 1 * FROM HR.EMPLOYEES e WHERE e.LAST_NAME = 'SMITH';

SELECT TOP 1 e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME FROM HR.EMPLOYEES e WHERE e.FIRST_NAME = 'Luis';
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.SALARY, e.DEPARTMENT_ID FROM HR.EMPLOYEES e WHERE e.SALARY > 10000 AND e.DEPARTMENT_ID <> 80;

SELECT e.FIRST_NAME, e.LAST_NAME FROM HR.EMPLOYEES e WHERE e.MANAGER_ID IS NULL;

SELECT * FROM hr.DEPARTMENTS d WHERE d.DEPARTMENT_NAME = 'IT';

SELECT * FROM HR.EMPLOYEES e WHERE e.DEPARTMENT_ID = (SELECT d.DEPARTMENT_ID FROM hr.DEPARTMENTS d WHERE d.DEPARTMENT_NAME = 'IT')

SELECT * FROM HR.EMPLOYEES e WHERE e.EMPLOYEE_ID = 703;

SELECT c.COLumn_NAME AS 'Mandatory Columns' FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = 'Employees' AND c.IS_NULLABLE = 'NO';

INSERT INTO HR.EMPLOYEES
    (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE, SALARY, PHONE_NUMBER,JOB_ID,DEPARTMENT_ID)
VALUES
    (703,'Luis','Gomes',GETDATE(),20000,'123.456.7890','IT_PROG',60);